name: β… CI

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: β… μ½”λ“ μ²΄ν¬ μ•„μ›ƒ
        uses: actions/checkout@v3

      - name: β… λ…Έλ“ μ„Έν…
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: π”¥ ν…μ¤νΈ
        run: npm test

      - name: π”¨ λΉλ“
        run: |
          npm ci
          npm run build
